load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

licenses(["notice"])

sh_binary(
    name = "mixed_language_module_map_extender",
    srcs = ["mixed_language_module_map_extender.pl"],
    visibility = ["//visibility:public"],
)
