# Copyright 2026 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Create the user reference-able repo that points to explicit module targets."""

_XCODE_VERSION_FLAG = "@bazel_tools//tools/osx:xcode_version_flag_exact"

# Mirrors `_SDK_CONSTRAINTS` in `tools/explicit_modules/scan.py`. Duplicated
# here because this Starlark file can't load Python data; kept in sync by hand.
_SDK_CONSTRAINTS = {
    "MacOSX": ["@platforms//os:macos"],
    "iPhoneOS": [
        "@platforms//os:ios",
        "@build_bazel_apple_support//constraints:device",
    ],
    "iPhoneSimulator": [
        "@platforms//os:ios",
        "@build_bazel_apple_support//constraints:simulator",
    ],
    "AppleTVOS": [
        "@platforms//os:tvos",
        "@build_bazel_apple_support//constraints:device",
    ],
    "AppleTVSimulator": [
        "@platforms//os:tvos",
        "@build_bazel_apple_support//constraints:simulator",
    ],
    "WatchOS": [
        "@platforms//os:watchos",
        "@build_bazel_apple_support//constraints:device",
    ],
    "WatchSimulator": [
        "@platforms//os:watchos",
        "@build_bazel_apple_support//constraints:simulator",
    ],
    "XROS": [
        "@platforms//os:visionos",
        "@build_bazel_apple_support//constraints:device",
    ],
    "XRSimulator": [
        "@platforms//os:visionos",
        "@build_bazel_apple_support//constraints:simulator",
    ],
}

def _sanitize(v):
    return v.replace(".", "_").replace("-", "_")

def _xcode_config_settings(versions):
    """Create a config_setting per Xcode version"""
    parts = []
    for version in versions:
        name = "xcode_{}".format(_sanitize(version))
        parts.append(
            """\
config_setting(
    name = "{}",
    flag_values = {{
        "{}": "{}",
    }},
)
""".format(name, _XCODE_VERSION_FLAG, version),
        )

    return "\n".join(parts)

def _render_sdk_config_settings(sdks):
    """Mirror per-Xcode SDK config_settings into the hub.

    Cross-import overlay selection keys these directly so they must live in
    the same repo as `cross_import_overlays.bzl`.
    """
    parts = []
    for sdk in sdks:
        constraints = _SDK_CONSTRAINTS.get(sdk)
        if not constraints:
            continue
        lines = [
            "config_setting(",
            '    name = "{}_sdk",'.format(sdk),
            "    constraint_values = [",
        ]
        for c in constraints:
            lines.append('        "{}",'.format(c))
        lines.append("    ],")
        lines.append(")")
        lines.append("")
        parts.append("\n".join(lines))
    return "\n".join(parts)

def _render_root_aliases(module_names, xcode_versions):
    """Given a list of module names, write out an alias to each Xcode version repo."""
    lines = []
    for name in sorted(module_names):
        lines.append("alias(")
        lines.append('    name = "{}",'.format(name))
        lines.append("    actual = select({")
        for version in xcode_versions:
            lines.append('        ":xcode_{v}": "@system_sdk_xcode_{v}//:{n}",'.format(
                v = _sanitize(version),
                n = name,
            ))
        lines.append("    }),")
        lines.append(")\n")
    return "\n".join(lines)

def _render_cross_import_overlays_bzl(overlays_by_sdk):
    """Render the hub's ``cross_import_overlays.bzl``.

    Every label here is local to the hub repo: SDK config_settings live in the
    hub's BUILD file (see `_render_sdk_config_settings`) and overlay targets
    are aliased into the hub (see `_render_overlay_aliases`). This keeps
    `Label(...)` resolution within the hub's own repo mapping, which sidesteps
    the Bzlmod visibility issue when the file is loaded from the autoconfig
    repo.
    """
    lines = [
        "# Generated by xcode_explicit_module_hub_repo - DO NOT EDIT.",
        "",
        "CROSS_IMPORT_OVERLAYS = select({",
    ]
    has_any = False
    for sdk in sorted(overlays_by_sdk.keys()):
        names = overlays_by_sdk[sdk]
        if not names:
            continue
        has_any = True
        lines.append('    Label("//:{sdk}_sdk"): ['.format(sdk = sdk))
        for name in names:
            lines.append('        Label("//:{name}"),'.format(name = name))
        lines.append("    ],")
    lines.append('    "//conditions:default": [],')
    lines.append("})")
    if not has_any:
        # Provide a no-op constant when nothing was scanned so consumers can
        # always `load(...)` and pass the symbol through.
        return "# Generated by xcode_explicit_module_hub_repo - DO NOT EDIT.\n\nCROSS_IMPORT_OVERLAYS = []\n"
    return "\n".join(lines) + "\n"

def _xcode_explicit_module_hub_repo_impl(rctx):
    xcode_versions = rctx.attr.xcode_versions
    manifest = json.decode(rctx.read(rctx.attr.default_manifest))
    rctx.watch(rctx.attr.default_manifest)

    root_module_names = {"all_modules": True}
    for name in manifest:
        root_module_names[name] = True

    overlays_by_sdk = {}
    if rctx.attr.default_overlays_json:
        overlays_by_sdk = json.decode(rctx.read(rctx.attr.default_overlays_json))
        rctx.watch(rctx.attr.default_overlays_json)

    sdks_with_overlays = sorted(
        [sdk for sdk, names in overlays_by_sdk.items() if names],
    )
    overlay_names = sorted({
        name: True
        for names in overlays_by_sdk.values()
        for name in names
    }.keys())

    xcode_settings_text = _xcode_config_settings(xcode_versions)
    sdk_settings_text = _render_sdk_config_settings(sdks_with_overlays)
    root_aliases_text = _render_root_aliases(
        root_module_names.keys(),
        xcode_versions,
    )
    overlay_aliases_text = _render_root_aliases(overlay_names, xcode_versions)

    rctx.file(
        "BUILD.bazel",
        'package(default_visibility = ["//visibility:public"])\n' +
        xcode_settings_text +
        sdk_settings_text +
        root_aliases_text +
        overlay_aliases_text,
    )

    rctx.file(
        "cross_import_overlays.bzl",
        _render_cross_import_overlays_bzl(overlays_by_sdk),
    )

xcode_explicit_module_hub_repo = repository_rule(
    implementation = _xcode_explicit_module_hub_repo_impl,
    attrs = {
        "xcode_versions": attr.string_list(
            mandatory = True,
            doc = "All canonical Xcode versions (default included).",
        ),
        "default_manifest": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "Label of the default repo's module_names.json.",
        ),
        "default_overlays_json": attr.label(
            mandatory = False,
            allow_single_file = True,
            doc = "Label of the default repo's cross_import_overlays.json.",
        ),
    },
    doc = "Export explicit module definitions referencing Xcode version specific repos.",
    environ = [
        "DEVELOPER_DIR",
        "XCODE_VERSION",
    ],
)
