load("@protobuf//bazel:proto_library.bzl", "proto_library")

proto_library(
    name = "example_proto",
    srcs = ["example.proto"],
    visibility = ["//examples/xplatform/custom_swift_proto_compiler:__subpackages__"],
)
