load("//swift:swift_library.bzl", "swift_library")

swift_library(
    name = "runfiles",
    srcs = [
        "Runfiles.swift",
    ],
    module_name = "BazelRunfiles",
    visibility = ["//visibility:public"],
)