// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker_protocol.proto
// Protobuf C++ Version: 7.34.0

#ifndef worker_5fprotocol_2eproto_2epb_2eh
#define worker_5fprotocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_worker_5fprotocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_worker_5fprotocol_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_worker_5fprotocol_2eproto;
}  // extern "C"
namespace blaze {
namespace worker {
class Input;
struct InputDefaultTypeInternal;
extern InputDefaultTypeInternal _Input_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Input_class_data_;
class WorkRequest;
struct WorkRequestDefaultTypeInternal;
extern WorkRequestDefaultTypeInternal _WorkRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WorkRequest_class_data_;
class WorkResponse;
struct WorkResponseDefaultTypeInternal;
extern WorkResponseDefaultTypeInternal _WorkResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WorkResponse_class_data_;
}  // namespace worker
}  // namespace blaze
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace blaze {
namespace worker {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED WorkResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:blaze.worker.WorkResponse) */ {
 public:
  inline WorkResponse() : WorkResponse(nullptr) {}
  ~WorkResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WorkResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WorkResponse));
  }
#endif

  template <typename = void>
  explicit constexpr WorkResponse(::google::protobuf::internal::ConstantInitialized);

  inline WorkResponse(const WorkResponse& from) : WorkResponse(nullptr, from) {}
  inline WorkResponse(WorkResponse&& from) noexcept
      : WorkResponse(nullptr, ::std::move(from)) {}
  inline WorkResponse& operator=(const WorkResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorkResponse& operator=(WorkResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const WorkResponse& default_instance() {
    return *reinterpret_cast<const WorkResponse*>(
        &_WorkResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(WorkResponse& a, WorkResponse& b) { a.Swap(&b); }
  inline void Swap(WorkResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorkResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] WorkResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WorkResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WorkResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WorkResponse& from) { WorkResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WorkResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "blaze.worker.WorkResponse"; }

  explicit WorkResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WorkResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WorkResponse& from);
  WorkResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WorkResponse&& from) noexcept
      : WorkResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOutputFieldNumber = 2,
    kExitCodeFieldNumber = 1,
    kRequestIdFieldNumber = 3,
    kWasCancelledFieldNumber = 4,
  };
  // string output = 2;
  void clear_output() ;
  [[nodiscard]] const ::std::string& output() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_output(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_output();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_output();
  void set_allocated_output(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_output() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_output(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_output();

  public:
  // int32 exit_code = 1;
  void clear_exit_code() ;
  [[nodiscard]] ::int32_t exit_code() const;
  void set_exit_code(::int32_t value);

  private:
  ::int32_t _internal_exit_code() const;
  void _internal_set_exit_code(::int32_t value);

  public:
  // int32 request_id = 3;
  void clear_request_id() ;
  [[nodiscard]] ::int32_t request_id() const;
  void set_request_id(::int32_t value);

  private:
  ::int32_t _internal_request_id() const;
  void _internal_set_request_id(::int32_t value);

  public:
  // bool was_cancelled = 4;
  void clear_was_cancelled() ;
  [[nodiscard]] bool was_cancelled() const;
  void set_was_cancelled(bool value);

  private:
  bool _internal_was_cancelled() const;
  void _internal_set_was_cancelled(bool value);

  public:
  // @@protoc_insertion_point(class_scope:blaze.worker.WorkResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 40,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WorkResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr output_;
    ::int32_t exit_code_;
    ::int32_t request_id_;
    bool was_cancelled_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_worker_5fprotocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WorkResponse_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Input final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:blaze.worker.Input) */ {
 public:
  inline Input() : Input(nullptr) {}
  ~Input() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Input* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Input));
  }
#endif

  template <typename = void>
  explicit constexpr Input(::google::protobuf::internal::ConstantInitialized);

  inline Input(const Input& from) : Input(nullptr, from) {}
  inline Input(Input&& from) noexcept
      : Input(nullptr, ::std::move(from)) {}
  inline Input& operator=(const Input& from) {
    CopyFrom(from);
    return *this;
  }
  inline Input& operator=(Input&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Input& default_instance() {
    return *reinterpret_cast<const Input*>(
        &_Input_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Input& a, Input& b) { a.Swap(&b); }
  inline void Swap(Input* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Input* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Input* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Input>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Input& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Input& from) { Input::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Input* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "blaze.worker.Input"; }

  explicit Input(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Input(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Input& from);
  Input(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Input&& from) noexcept
      : Input(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPathFieldNumber = 1,
    kDigestFieldNumber = 2,
  };
  // string path = 1;
  void clear_path() ;
  [[nodiscard]] const ::std::string& path() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_path(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_path();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_path();
  void set_allocated_path(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_path(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_path();

  public:
  // bytes digest = 2;
  void clear_digest() ;
  [[nodiscard]] const ::std::string& digest() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_digest(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_digest();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_digest();
  void set_allocated_digest(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_digest() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_digest(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_digest();

  public:
  // @@protoc_insertion_point(class_scope:blaze.worker.Input)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Input& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr path_;
    ::google::protobuf::internal::ArenaStringPtr digest_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_worker_5fprotocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Input_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED WorkRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:blaze.worker.WorkRequest) */ {
 public:
  inline WorkRequest() : WorkRequest(nullptr) {}
  ~WorkRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WorkRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WorkRequest));
  }
#endif

  template <typename = void>
  explicit constexpr WorkRequest(::google::protobuf::internal::ConstantInitialized);

  inline WorkRequest(const WorkRequest& from) : WorkRequest(nullptr, from) {}
  inline WorkRequest(WorkRequest&& from) noexcept
      : WorkRequest(nullptr, ::std::move(from)) {}
  inline WorkRequest& operator=(const WorkRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorkRequest& operator=(WorkRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const WorkRequest& default_instance() {
    return *reinterpret_cast<const WorkRequest*>(
        &_WorkRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(WorkRequest& a, WorkRequest& b) { a.Swap(&b); }
  inline void Swap(WorkRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorkRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] WorkRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WorkRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WorkRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WorkRequest& from) { WorkRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WorkRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "blaze.worker.WorkRequest"; }

  explicit WorkRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WorkRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WorkRequest& from);
  WorkRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WorkRequest&& from) noexcept
      : WorkRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kArgumentsFieldNumber = 1,
    kInputsFieldNumber = 2,
    kSandboxDirFieldNumber = 6,
    kRequestIdFieldNumber = 3,
    kCancelFieldNumber = 4,
    kVerbosityFieldNumber = 5,
  };
  // repeated string arguments = 1;
  [[nodiscard]] int arguments_size()
      const;
  private:
  int _internal_arguments_size() const;

  public:
  void clear_arguments() ;
  [[nodiscard]] const ::std::string& arguments(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_arguments(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_arguments(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_arguments();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_arguments(Arg_&& value, Args_... args);
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::std::string>&
  arguments() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
  mutable_arguments();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_arguments() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_arguments();

  public:
  // repeated .blaze.worker.Input inputs = 2;
  [[nodiscard]] int inputs_size()
      const;
  private:
  int _internal_inputs_size() const;

  public:
  void clear_inputs() ;
  [[nodiscard]] ::blaze::worker::Input* PROTOBUF_NONNULL mutable_inputs(int index);
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::blaze::worker::Input>* PROTOBUF_NONNULL
  mutable_inputs();

  private:
  const ::google::protobuf::RepeatedPtrField<::blaze::worker::Input>& _internal_inputs() const;
  ::google::protobuf::RepeatedPtrField<::blaze::worker::Input>* PROTOBUF_NONNULL _internal_mutable_inputs();
  public:
  [[nodiscard]] const ::blaze::worker::Input& inputs(int index) const;
  ::blaze::worker::Input* PROTOBUF_NONNULL add_inputs();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::blaze::worker::Input>& inputs()
      const;
  // string sandbox_dir = 6;
  void clear_sandbox_dir() ;
  [[nodiscard]] const ::std::string& sandbox_dir() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sandbox_dir(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sandbox_dir();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sandbox_dir();
  void set_allocated_sandbox_dir(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sandbox_dir() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sandbox_dir(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sandbox_dir();

  public:
  // int32 request_id = 3;
  void clear_request_id() ;
  [[nodiscard]] ::int32_t request_id() const;
  void set_request_id(::int32_t value);

  private:
  ::int32_t _internal_request_id() const;
  void _internal_set_request_id(::int32_t value);

  public:
  // bool cancel = 4;
  void clear_cancel() ;
  [[nodiscard]] bool cancel() const;
  void set_cancel(bool value);

  private:
  bool _internal_cancel() const;
  void _internal_set_cancel(bool value);

  public:
  // int32 verbosity = 5;
  void clear_verbosity() ;
  [[nodiscard]] ::int32_t verbosity() const;
  void set_verbosity(::int32_t value);

  private:
  ::int32_t _internal_verbosity() const;
  void _internal_set_verbosity(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:blaze.worker.WorkRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   1, 53,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WorkRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> arguments_;
    ::google::protobuf::RepeatedPtrField< ::blaze::worker::Input > inputs_;
    ::google::protobuf::internal::ArenaStringPtr sandbox_dir_;
    ::int32_t request_id_;
    bool cancel_;
    ::int32_t verbosity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_worker_5fprotocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WorkRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Input

// string path = 1;
inline void Input::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Input::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:blaze.worker.Input.path)
  return _internal_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Input::set_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:blaze.worker.Input.path)
}
inline ::std::string* PROTOBUF_NONNULL Input::mutable_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:blaze.worker.Input.path)
  return _s;
}
inline const ::std::string& Input::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_.Get();
}
inline void Input::_internal_set_path(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Input::_internal_mutable_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.path_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Input::release_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:blaze.worker.Input.path)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.path_.Set("", GetArena());
  }
  return released;
}
inline void Input::set_allocated_path(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:blaze.worker.Input.path)
}

// bytes digest = 2;
inline void Input::clear_digest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.digest_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Input::digest() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:blaze.worker.Input.digest)
  return _internal_digest();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Input::set_digest(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.digest_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:blaze.worker.Input.digest)
}
inline ::std::string* PROTOBUF_NONNULL Input::mutable_digest()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_digest();
  // @@protoc_insertion_point(field_mutable:blaze.worker.Input.digest)
  return _s;
}
inline const ::std::string& Input::_internal_digest() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.digest_.Get();
}
inline void Input::_internal_set_digest(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.digest_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Input::_internal_mutable_digest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.digest_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Input::release_digest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:blaze.worker.Input.digest)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.digest_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.digest_.Set("", GetArena());
  }
  return released;
}
inline void Input::set_allocated_digest(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.digest_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.digest_.IsDefault()) {
    _impl_.digest_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:blaze.worker.Input.digest)
}

// -------------------------------------------------------------------

// WorkRequest

// repeated string arguments = 1;
inline int WorkRequest::_internal_arguments_size() const {
  return _internal_arguments().size();
}
inline int WorkRequest::arguments_size() const {
  return _internal_arguments_size();
}
inline void WorkRequest::clear_arguments() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arguments_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL WorkRequest::add_arguments()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_arguments()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:blaze.worker.WorkRequest.arguments)
  return _s;
}
inline const ::std::string& WorkRequest::arguments(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkRequest.arguments)
  return _internal_arguments().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL WorkRequest::mutable_arguments(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:blaze.worker.WorkRequest.arguments)
  return _internal_mutable_arguments()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void WorkRequest::set_arguments(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_arguments()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:blaze.worker.WorkRequest.arguments)
}
template <typename Arg_, typename... Args_>
inline void WorkRequest::add_arguments(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_arguments(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:blaze.worker.WorkRequest.arguments)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& WorkRequest::arguments()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:blaze.worker.WorkRequest.arguments)
  return _internal_arguments();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
WorkRequest::mutable_arguments() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:blaze.worker.WorkRequest.arguments)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_arguments();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
WorkRequest::_internal_arguments() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.arguments_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
WorkRequest::_internal_mutable_arguments() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.arguments_;
}

// repeated .blaze.worker.Input inputs = 2;
inline int WorkRequest::_internal_inputs_size() const {
  return _internal_inputs().size();
}
inline int WorkRequest::inputs_size() const {
  return _internal_inputs_size();
}
inline void WorkRequest::clear_inputs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.inputs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::blaze::worker::Input* PROTOBUF_NONNULL WorkRequest::mutable_inputs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:blaze.worker.WorkRequest.inputs)
  return _internal_mutable_inputs()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::blaze::worker::Input>* PROTOBUF_NONNULL WorkRequest::mutable_inputs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:blaze.worker.WorkRequest.inputs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_inputs();
}
inline const ::blaze::worker::Input& WorkRequest::inputs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkRequest.inputs)
  return _internal_inputs().Get(index);
}
inline ::blaze::worker::Input* PROTOBUF_NONNULL WorkRequest::add_inputs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::blaze::worker::Input* _add =
      _internal_mutable_inputs()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:blaze.worker.WorkRequest.inputs)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::blaze::worker::Input>& WorkRequest::inputs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:blaze.worker.WorkRequest.inputs)
  return _internal_inputs();
}
inline const ::google::protobuf::RepeatedPtrField<::blaze::worker::Input>&
WorkRequest::_internal_inputs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.inputs_;
}
inline ::google::protobuf::RepeatedPtrField<::blaze::worker::Input>* PROTOBUF_NONNULL
WorkRequest::_internal_mutable_inputs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.inputs_;
}

// int32 request_id = 3;
inline void WorkRequest::clear_request_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t WorkRequest::request_id() const {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkRequest.request_id)
  return _internal_request_id();
}
inline void WorkRequest::set_request_id(::int32_t value) {
  _internal_set_request_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:blaze.worker.WorkRequest.request_id)
}
inline ::int32_t WorkRequest::_internal_request_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.request_id_;
}
inline void WorkRequest::_internal_set_request_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_id_ = value;
}

// bool cancel = 4;
inline void WorkRequest::clear_cancel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cancel_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool WorkRequest::cancel() const {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkRequest.cancel)
  return _internal_cancel();
}
inline void WorkRequest::set_cancel(bool value) {
  _internal_set_cancel(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:blaze.worker.WorkRequest.cancel)
}
inline bool WorkRequest::_internal_cancel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cancel_;
}
inline void WorkRequest::_internal_set_cancel(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cancel_ = value;
}

// int32 verbosity = 5;
inline void WorkRequest::clear_verbosity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verbosity_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t WorkRequest::verbosity() const {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkRequest.verbosity)
  return _internal_verbosity();
}
inline void WorkRequest::set_verbosity(::int32_t value) {
  _internal_set_verbosity(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:blaze.worker.WorkRequest.verbosity)
}
inline ::int32_t WorkRequest::_internal_verbosity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.verbosity_;
}
inline void WorkRequest::_internal_set_verbosity(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verbosity_ = value;
}

// string sandbox_dir = 6;
inline void WorkRequest::clear_sandbox_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sandbox_dir_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& WorkRequest::sandbox_dir() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkRequest.sandbox_dir)
  return _internal_sandbox_dir();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void WorkRequest::set_sandbox_dir(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.sandbox_dir_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:blaze.worker.WorkRequest.sandbox_dir)
}
inline ::std::string* PROTOBUF_NONNULL WorkRequest::mutable_sandbox_dir()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_sandbox_dir();
  // @@protoc_insertion_point(field_mutable:blaze.worker.WorkRequest.sandbox_dir)
  return _s;
}
inline const ::std::string& WorkRequest::_internal_sandbox_dir() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sandbox_dir_.Get();
}
inline void WorkRequest::_internal_set_sandbox_dir(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sandbox_dir_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL WorkRequest::_internal_mutable_sandbox_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sandbox_dir_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE WorkRequest::release_sandbox_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:blaze.worker.WorkRequest.sandbox_dir)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.sandbox_dir_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sandbox_dir_.Set("", GetArena());
  }
  return released;
}
inline void WorkRequest::set_allocated_sandbox_dir(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.sandbox_dir_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sandbox_dir_.IsDefault()) {
    _impl_.sandbox_dir_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:blaze.worker.WorkRequest.sandbox_dir)
}

// -------------------------------------------------------------------

// WorkResponse

// int32 exit_code = 1;
inline void WorkResponse::clear_exit_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exit_code_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t WorkResponse::exit_code() const {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkResponse.exit_code)
  return _internal_exit_code();
}
inline void WorkResponse::set_exit_code(::int32_t value) {
  _internal_set_exit_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:blaze.worker.WorkResponse.exit_code)
}
inline ::int32_t WorkResponse::_internal_exit_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exit_code_;
}
inline void WorkResponse::_internal_set_exit_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exit_code_ = value;
}

// string output = 2;
inline void WorkResponse::clear_output() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.output_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& WorkResponse::output() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkResponse.output)
  return _internal_output();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void WorkResponse::set_output(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.output_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:blaze.worker.WorkResponse.output)
}
inline ::std::string* PROTOBUF_NONNULL WorkResponse::mutable_output()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_output();
  // @@protoc_insertion_point(field_mutable:blaze.worker.WorkResponse.output)
  return _s;
}
inline const ::std::string& WorkResponse::_internal_output() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.output_.Get();
}
inline void WorkResponse::_internal_set_output(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.output_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL WorkResponse::_internal_mutable_output() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.output_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE WorkResponse::release_output() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:blaze.worker.WorkResponse.output)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.output_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.output_.Set("", GetArena());
  }
  return released;
}
inline void WorkResponse::set_allocated_output(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.output_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.output_.IsDefault()) {
    _impl_.output_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:blaze.worker.WorkResponse.output)
}

// int32 request_id = 3;
inline void WorkResponse::clear_request_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t WorkResponse::request_id() const {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkResponse.request_id)
  return _internal_request_id();
}
inline void WorkResponse::set_request_id(::int32_t value) {
  _internal_set_request_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:blaze.worker.WorkResponse.request_id)
}
inline ::int32_t WorkResponse::_internal_request_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.request_id_;
}
inline void WorkResponse::_internal_set_request_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_id_ = value;
}

// bool was_cancelled = 4;
inline void WorkResponse::clear_was_cancelled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.was_cancelled_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool WorkResponse::was_cancelled() const {
  // @@protoc_insertion_point(field_get:blaze.worker.WorkResponse.was_cancelled)
  return _internal_was_cancelled();
}
inline void WorkResponse::set_was_cancelled(bool value) {
  _internal_set_was_cancelled(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:blaze.worker.WorkResponse.was_cancelled)
}
inline bool WorkResponse::_internal_was_cancelled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.was_cancelled_;
}
inline void WorkResponse::_internal_set_was_cancelled(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.was_cancelled_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace worker
}  // namespace blaze


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // worker_5fprotocol_2eproto_2epb_2eh
