// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker_protocol.proto
// Protobuf C++ Version: 7.34.0

#include "worker_protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace blaze {
namespace worker {

inline constexpr WorkResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        output_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        exit_code_{0},
        request_id_{0},
        was_cancelled_{false} {}

template <typename>
constexpr WorkResponse::WorkResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WorkResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct WorkResponseDefaultTypeInternal {
  constexpr WorkResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WorkResponseDefaultTypeInternal() {}
  union {
    WorkResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WorkResponseDefaultTypeInternal _WorkResponse_default_instance_;

inline constexpr Input::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        digest_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr Input::Input(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Input_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct InputDefaultTypeInternal {
  constexpr InputDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InputDefaultTypeInternal() {}
  union {
    Input _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InputDefaultTypeInternal _Input_default_instance_;

inline constexpr WorkRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        arguments_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::blaze::worker::WorkRequest,
            PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.arguments_)>()
        }
        #else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        arguments_ {}
        #endif
        ,
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        inputs_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::blaze::worker::WorkRequest,
            PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.inputs_)>()
        }
        #else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        inputs_ {}
        #endif
        ,
        sandbox_dir_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        request_id_{0},
        cancel_{false},
        verbosity_{0} {}

template <typename>
constexpr WorkRequest::WorkRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WorkRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct WorkRequestDefaultTypeInternal {
  constexpr WorkRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WorkRequestDefaultTypeInternal() {}
  union {
    WorkRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WorkRequestDefaultTypeInternal _WorkRequest_default_instance_;
}  // namespace worker
}  // namespace blaze
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_worker_5fprotocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_worker_5fprotocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_worker_5fprotocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::blaze::worker::Input, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::blaze::worker::Input, _impl_.path_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::Input, _impl_.digest_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.arguments_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.inputs_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.request_id_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.cancel_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.verbosity_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.sandbox_dir_),
        0,
        1,
        3,
        4,
        5,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkResponse, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkResponse, _impl_.exit_code_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkResponse, _impl_.output_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkResponse, _impl_.request_id_),
        PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkResponse, _impl_.was_cancelled_),
        1,
        0,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::blaze::worker::Input)},
        {7, sizeof(::blaze::worker::WorkRequest)},
        {22, sizeof(::blaze::worker::WorkResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::blaze::worker::_Input_default_instance_._instance,
    &::blaze::worker::_WorkRequest_default_instance_._instance,
    &::blaze::worker::_WorkResponse_default_instance_._instance,
};
const char descriptor_table_protodef_worker_5fprotocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025worker_protocol.proto\022\014blaze.worker\"%\n"
    "\005Input\022\014\n\004path\030\001 \001(\t\022\016\n\006digest\030\002 \001(\014\"\221\001\n"
    "\013WorkRequest\022\021\n\targuments\030\001 \003(\t\022#\n\006input"
    "s\030\002 \003(\0132\023.blaze.worker.Input\022\022\n\nrequest_"
    "id\030\003 \001(\005\022\016\n\006cancel\030\004 \001(\010\022\021\n\tverbosity\030\005 "
    "\001(\005\022\023\n\013sandbox_dir\030\006 \001(\t\"\\\n\014WorkResponse"
    "\022\021\n\texit_code\030\001 \001(\005\022\016\n\006output\030\002 \001(\t\022\022\n\nr"
    "equest_id\030\003 \001(\005\022\025\n\rwas_cancelled\030\004 \001(\010B&"
    "\n$com.google.devtools.build.lib.workerb\006"
    "proto3"
};
static ::absl::once_flag descriptor_table_worker_5fprotocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_worker_5fprotocol_2eproto = {
    false,
    false,
    366,
    descriptor_table_protodef_worker_5fprotocol_2eproto,
    "worker_protocol.proto",
    &descriptor_table_worker_5fprotocol_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_worker_5fprotocol_2eproto::offsets,
    file_level_enum_descriptors_worker_5fprotocol_2eproto,
    file_level_service_descriptors_worker_5fprotocol_2eproto,
};
namespace blaze {
namespace worker {
// ===================================================================

class Input::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Input>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Input, _impl_._has_bits_);
};

Input::Input(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Input_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:blaze.worker.Input)
}
PROTOBUF_NDEBUG_INLINE Input::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::blaze::worker::Input& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        path_(arena, from.path_),
        digest_(arena, from.digest_) {}

Input::Input(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Input& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Input_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Input* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:blaze.worker.Input)
}
PROTOBUF_NDEBUG_INLINE Input::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        path_(arena),
        digest_(arena) {}

inline void Input::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Input::~Input() {
  // @@protoc_insertion_point(destructor:blaze.worker.Input)
  SharedDtor(*this);
}
inline void Input::SharedDtor(MessageLite& self) {
  Input& this_ = static_cast<Input&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.path_.Destroy();
  this_._impl_.digest_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Input::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Input(arena);
}
constexpr auto Input::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Input),
                                            alignof(Input));
}
constexpr auto Input::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Input_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &Input::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Input>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Input::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Input>(), &Input::ByteSizeLong,
              &Input::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Input, _impl_._cached_size_),
          false,
      },
      &Input::kDescriptorMethods,
      &descriptor_table_worker_5fprotocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Input_class_data_ =
        Input::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Input::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Input_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Input_class_data_.tc_table);
  return Input_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 31, 2>
Input::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Input, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Input_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::blaze::worker::Input>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes digest = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(Input, _impl_.digest_)}},
    // string path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Input, _impl_.path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string path = 1;
    {PROTOBUF_FIELD_OFFSET(Input, _impl_.path_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes digest = 2;
    {PROTOBUF_FIELD_OFFSET(Input, _impl_.digest_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\4\0\0\0\0\0\0"
    "blaze.worker.Input"
    "path"
  }},
};
PROTOBUF_NOINLINE void Input::Clear() {
// @@protoc_insertion_point(message_clear_start:blaze.worker.Input)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.path_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.digest_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Input::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Input& this_ = static_cast<const Input&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Input::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Input& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:blaze.worker.Input)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string path = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_path().empty()) {
      const ::std::string& _s = this_._internal_path();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "blaze.worker.Input.path");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // bytes digest = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_digest().empty()) {
      const ::std::string& _s = this_._internal_digest();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:blaze.worker.Input)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Input::ByteSizeLong(const MessageLite& base) {
  const Input& this_ = static_cast<const Input&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Input::ByteSizeLong() const {
  const Input& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:blaze.worker.Input)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string path = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_path().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_path());
      }
    }
    // bytes digest = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_digest().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_digest());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Input::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Input*>(&to_msg);
  auto& from = static_cast<const Input&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:blaze.worker.Input)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_path().empty()) {
        _this->_internal_set_path(from._internal_path());
      } else {
        if (_this->_impl_.path_.IsDefault()) {
          _this->_internal_set_path("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_digest().empty()) {
        _this->_internal_set_digest(from._internal_digest());
      } else {
        if (_this->_impl_.digest_.IsDefault()) {
          _this->_internal_set_digest("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Input::CopyFrom(const Input& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:blaze.worker.Input)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Input::InternalSwap(Input* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.digest_, &other->_impl_.digest_, arena);
}

::google::protobuf::Metadata Input::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WorkRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WorkRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_._has_bits_);
};

WorkRequest::WorkRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WorkRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:blaze.worker.WorkRequest)
}
PROTOBUF_NDEBUG_INLINE WorkRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::blaze::worker::WorkRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        arguments_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::blaze::worker::WorkRequest,
            PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.arguments_)>()
        , from.arguments_}
        #else
        arguments_ { visibility, arena, from.arguments_ }
        #endif
        ,
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        inputs_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::blaze::worker::WorkRequest,
            PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.inputs_)>()
        , from.inputs_}
        #else
        inputs_ { visibility, arena, from.inputs_ }
        #endif
        ,
        sandbox_dir_(arena, from.sandbox_dir_) {}

WorkRequest::WorkRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WorkRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WorkRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WorkRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, request_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, request_id_),
           offsetof(Impl_, verbosity_) -
               offsetof(Impl_, request_id_) +
               sizeof(Impl_::verbosity_));

  // @@protoc_insertion_point(copy_constructor:blaze.worker.WorkRequest)
}
PROTOBUF_NDEBUG_INLINE WorkRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        arguments_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::blaze::worker::WorkRequest,
            PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.arguments_)>()
        }
        #else
        arguments_ { visibility, arena }
        #endif
        ,
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        inputs_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::blaze::worker::WorkRequest,
            PROTOBUF_FIELD_OFFSET(::blaze::worker::WorkRequest, _impl_.inputs_)>()
        }
        #else
        inputs_ { visibility, arena }
        #endif
        ,
        sandbox_dir_(arena) {}

inline void WorkRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, request_id_),
           0,
           offsetof(Impl_, verbosity_) -
               offsetof(Impl_, request_id_) +
               sizeof(Impl_::verbosity_));
}
WorkRequest::~WorkRequest() {
  // @@protoc_insertion_point(destructor:blaze.worker.WorkRequest)
  SharedDtor(*this);
}
inline void WorkRequest::SharedDtor(MessageLite& self) {
  WorkRequest& this_ = static_cast<WorkRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sandbox_dir_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WorkRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WorkRequest(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto WorkRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WorkRequest),
                                            alignof(WorkRequest));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto WorkRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.arguments_) +
          decltype(WorkRequest::_impl_.arguments_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.inputs_) +
          decltype(WorkRequest::_impl_.inputs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(WorkRequest), alignof(WorkRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&WorkRequest::PlacementNew_,
                                 sizeof(WorkRequest),
                                 alignof(WorkRequest));
  }
}
#endif
constexpr auto WorkRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WorkRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &WorkRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WorkRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WorkRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WorkRequest>(), &WorkRequest::ByteSizeLong,
              &WorkRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_._cached_size_),
          false,
      },
      &WorkRequest::kDescriptorMethods,
      &descriptor_table_worker_5fprotocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WorkRequest_class_data_ =
        WorkRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WorkRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WorkRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WorkRequest_class_data_.tc_table);
  return WorkRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 53, 2>
WorkRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    WorkRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::blaze::worker::WorkRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated string arguments = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.arguments_)}},
    // repeated .blaze.worker.Input inputs = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.inputs_)}},
    // int32 request_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WorkRequest, _impl_.request_id_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.request_id_)}},
    // bool cancel = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WorkRequest, _impl_.cancel_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.cancel_)}},
    // int32 verbosity = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WorkRequest, _impl_.verbosity_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.verbosity_)}},
    // string sandbox_dir = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 2, 0,
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.sandbox_dir_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string arguments = 1;
    {PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.arguments_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated .blaze.worker.Input inputs = 2;
    {PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.inputs_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 request_id = 3;
    {PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.request_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bool cancel = 4;
    {PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.cancel_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // int32 verbosity = 5;
    {PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.verbosity_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string sandbox_dir = 6;
    {PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.sandbox_dir_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::blaze::worker::Input>()},
  }},
  {{
    "\30\11\0\0\0\0\13\0"
    "blaze.worker.WorkRequest"
    "arguments"
    "sandbox_dir"
  }},
};
PROTOBUF_NOINLINE void WorkRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:blaze.worker.WorkRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.arguments_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.inputs_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.sandbox_dir_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000038U)) {
    ::memset(&_impl_.request_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.verbosity_) -
        reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.verbosity_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WorkRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WorkRequest& this_ = static_cast<const WorkRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WorkRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WorkRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:blaze.worker.WorkRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated string arguments = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_arguments_size(); i < n; ++i) {
      const auto& s = this_._internal_arguments().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "blaze.worker.WorkRequest.arguments");
      target = stream->WriteString(1, s, target);
    }
  }

  // repeated .blaze.worker.Input inputs = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_inputs_size());
         i < n; i++) {
      const auto& repfield = this_._internal_inputs().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // int32 request_id = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_request_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_request_id(), target);
    }
  }

  // bool cancel = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_cancel() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_cancel(), target);
    }
  }

  // int32 verbosity = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_verbosity() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_verbosity(), target);
    }
  }

  // string sandbox_dir = 6;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_sandbox_dir().empty()) {
      const ::std::string& _s = this_._internal_sandbox_dir();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "blaze.worker.WorkRequest.sandbox_dir");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:blaze.worker.WorkRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WorkRequest::ByteSizeLong(const MessageLite& base) {
  const WorkRequest& this_ = static_cast<const WorkRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WorkRequest::ByteSizeLong() const {
  const WorkRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:blaze.worker.WorkRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // repeated string arguments = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_arguments().size());
      for (int i = 0, n = this_._internal_arguments().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_arguments().Get(i));
      }
    }
    // repeated .blaze.worker.Input inputs = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_inputs_size();
      for (const auto& msg : this_._internal_inputs()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string sandbox_dir = 6;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_sandbox_dir().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_sandbox_dir());
      }
    }
    // int32 request_id = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_request_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_request_id());
      }
    }
    // bool cancel = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_cancel() != 0) {
        total_size += 2;
      }
    }
    // int32 verbosity = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_verbosity() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_verbosity());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WorkRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<WorkRequest*>(&to_msg);
  auto& from = static_cast<const WorkRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:blaze.worker.WorkRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_arguments()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_arguments());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_inputs()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_inputs());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_sandbox_dir().empty()) {
        _this->_internal_set_sandbox_dir(from._internal_sandbox_dir());
      } else {
        if (_this->_impl_.sandbox_dir_.IsDefault()) {
          _this->_internal_set_sandbox_dir("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_request_id() != 0) {
        _this->_impl_.request_id_ = from._impl_.request_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_cancel() != 0) {
        _this->_impl_.cancel_ = from._impl_.cancel_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_verbosity() != 0) {
        _this->_impl_.verbosity_ = from._impl_.verbosity_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void WorkRequest::CopyFrom(const WorkRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:blaze.worker.WorkRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WorkRequest::InternalSwap(WorkRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.arguments_.InternalSwap(&other->_impl_.arguments_);
  _impl_.inputs_.InternalSwap(&other->_impl_.inputs_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sandbox_dir_, &other->_impl_.sandbox_dir_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.verbosity_)
      + sizeof(WorkRequest::_impl_.verbosity_)
      - PROTOBUF_FIELD_OFFSET(WorkRequest, _impl_.request_id_)>(
          reinterpret_cast<char*>(&_impl_.request_id_),
          reinterpret_cast<char*>(&other->_impl_.request_id_));
}

::google::protobuf::Metadata WorkRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WorkResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WorkResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_._has_bits_);
};

WorkResponse::WorkResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WorkResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:blaze.worker.WorkResponse)
}
PROTOBUF_NDEBUG_INLINE WorkResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::blaze::worker::WorkResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        output_(arena, from.output_) {}

WorkResponse::WorkResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WorkResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WorkResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WorkResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, exit_code_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, exit_code_),
           offsetof(Impl_, was_cancelled_) -
               offsetof(Impl_, exit_code_) +
               sizeof(Impl_::was_cancelled_));

  // @@protoc_insertion_point(copy_constructor:blaze.worker.WorkResponse)
}
PROTOBUF_NDEBUG_INLINE WorkResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        output_(arena) {}

inline void WorkResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, exit_code_),
           0,
           offsetof(Impl_, was_cancelled_) -
               offsetof(Impl_, exit_code_) +
               sizeof(Impl_::was_cancelled_));
}
WorkResponse::~WorkResponse() {
  // @@protoc_insertion_point(destructor:blaze.worker.WorkResponse)
  SharedDtor(*this);
}
inline void WorkResponse::SharedDtor(MessageLite& self) {
  WorkResponse& this_ = static_cast<WorkResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.output_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WorkResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WorkResponse(arena);
}
constexpr auto WorkResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WorkResponse),
                                            alignof(WorkResponse));
}
constexpr auto WorkResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WorkResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &WorkResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WorkResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WorkResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WorkResponse>(), &WorkResponse::ByteSizeLong,
              &WorkResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_._cached_size_),
          false,
      },
      &WorkResponse::kDescriptorMethods,
      &descriptor_table_worker_5fprotocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WorkResponse_class_data_ =
        WorkResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WorkResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WorkResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WorkResponse_class_data_.tc_table);
  return WorkResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 40, 2>
WorkResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WorkResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::blaze::worker::WorkResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool was_cancelled = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WorkResponse, _impl_.was_cancelled_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.was_cancelled_)}},
    // int32 exit_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WorkResponse, _impl_.exit_code_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.exit_code_)}},
    // string output = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.output_)}},
    // int32 request_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WorkResponse, _impl_.request_id_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.request_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 exit_code = 1;
    {PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.exit_code_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string output = 2;
    {PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.output_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 request_id = 3;
    {PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.request_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bool was_cancelled = 4;
    {PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.was_cancelled_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\31\0\6\0\0\0\0\0"
    "blaze.worker.WorkResponse"
    "output"
  }},
};
PROTOBUF_NOINLINE void WorkResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:blaze.worker.WorkResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.output_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000eU)) {
    ::memset(&_impl_.exit_code_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.was_cancelled_) -
        reinterpret_cast<char*>(&_impl_.exit_code_)) + sizeof(_impl_.was_cancelled_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WorkResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WorkResponse& this_ = static_cast<const WorkResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WorkResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WorkResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:blaze.worker.WorkResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 exit_code = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_exit_code() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_exit_code(), target);
    }
  }

  // string output = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_output().empty()) {
      const ::std::string& _s = this_._internal_output();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "blaze.worker.WorkResponse.output");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int32 request_id = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_request_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_request_id(), target);
    }
  }

  // bool was_cancelled = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_was_cancelled() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_was_cancelled(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:blaze.worker.WorkResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WorkResponse::ByteSizeLong(const MessageLite& base) {
  const WorkResponse& this_ = static_cast<const WorkResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WorkResponse::ByteSizeLong() const {
  const WorkResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:blaze.worker.WorkResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string output = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_output().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_output());
      }
    }
    // int32 exit_code = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_exit_code() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_exit_code());
      }
    }
    // int32 request_id = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_request_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_request_id());
      }
    }
    // bool was_cancelled = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_was_cancelled() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WorkResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<WorkResponse*>(&to_msg);
  auto& from = static_cast<const WorkResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:blaze.worker.WorkResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_output().empty()) {
        _this->_internal_set_output(from._internal_output());
      } else {
        if (_this->_impl_.output_.IsDefault()) {
          _this->_internal_set_output("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_exit_code() != 0) {
        _this->_impl_.exit_code_ = from._impl_.exit_code_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_request_id() != 0) {
        _this->_impl_.request_id_ = from._impl_.request_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_was_cancelled() != 0) {
        _this->_impl_.was_cancelled_ = from._impl_.was_cancelled_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void WorkResponse::CopyFrom(const WorkResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:blaze.worker.WorkResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WorkResponse::InternalSwap(WorkResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.output_, &other->_impl_.output_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.was_cancelled_)
      + sizeof(WorkResponse::_impl_.was_cancelled_)
      - PROTOBUF_FIELD_OFFSET(WorkResponse, _impl_.exit_code_)>(
          reinterpret_cast<char*>(&_impl_.exit_code_),
          reinterpret_cast<char*>(&other->_impl_.exit_code_));
}

::google::protobuf::Metadata WorkResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace worker
}  // namespace blaze
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_worker_5fprotocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
