"""Aliases to provided proto compiler targets."""

alias(
    name = "swift_proto",
    actual = "//swift/proto/compilers:swift_proto",
    visibility = ["//visibility:public"],
)

alias(
    name = "swift_grpc",
    actual = "//swift/proto/compilers:swift_grpc",
    visibility = ["//visibility:public"],
)

alias(
    name = "swift_server_grpc",
    actual = "//swift/proto/compilers:swift_server_grpc",
    visibility = ["//visibility:public"],
)

alias(
    name = "swift_client_grpc",
    actual = "//swift/proto/compilers:swift_client_grpc",
    visibility = ["//visibility:public"],
)

alias(
    name = "swift_test_client_grpc",
    actual = "//swift/proto/compilers:swift_test_client_grpc",
    visibility = ["//visibility:public"],
)