load("//swift:swift.bzl", "swift_binary", "swift_test")

swift_binary(
    name = "coverage",
    srcs = ["main.swift"],
)

swift_test(
    name = "tests",
    srcs = [
        "tests.swift",
    ],
)
