load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

bzl_library(
    name = "proto",
    srcs = ["proto.bzl"],
    deps = [
        "//swift",
    ],
)
