load("//swift:swift.bzl", "swift_binary")

swift_binary(
    name = "test_discoverer",
    srcs = [
        "DiscoveredTests.swift",
        "SymbolCollector.swift",
        "SymbolKitExtensions.swift",
        "TestDiscoverer.swift",
        "TestPrinter.swift",
    ],
    visibility = ["//visibility:public"],
)
