load(
    "//swift:swift_binary.bzl",
    "swift_binary",
)

swift_binary(
    name = "test_discoverer",
    srcs = [
        "DiscoveredTests.swift",
        "ObjcTestPrinter.swift",
        "SymbolCollector.swift",
        "SymbolGraphTestPrinter.swift",
        "SymbolKitExtensions.swift",
        "TestDiscoverer.swift",
        "TestPrinterCommon.swift",
    ],
    visibility = ["//visibility:public"],
)
