// Copyright 2026 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import XCTest

#if !canImport(ObjectiveC)
  /// This function is generated by the `test_discoverer` tool and contains the XCTests that were
  /// discovered based on the symbol graphs of the target's dependencies.
  @_silgen_name("bazel_rules_swift_allDiscoveredXCTests")
  internal func allDiscoveredXCTests() -> [XCTestCaseEntry]
#endif

@available(
  *,
  deprecated,
  message: """
    Not actually deprecated. Marked as deprecated to allow inclusion of deprecated tests (which \
    test deprecated functionality) without warnings.
    """
)
@main
struct TestRunnerMain {
  static func main() {
    // These async shenanigans are necessary because `XCTestSuite.default.run()` doesn't like to be
    // called from an `async main()` (it crashes in the runtime's stack allocator if it tries to run
    // an async test method), but we have to do async work to run swift-testing tests. See
    // https://forums.swift.org/t/74010 for additional context.
    do {
      #if canImport(ObjectiveC)
        // The Objective-C runner doesn't take any arguments, since it uses the runtime to discover
        // tests.
        try XCTestRunner.run()
      #else
        try XCTestRunner.run(allDiscoveredXCTests())
      #endif
    } catch {
      print("Fatal error running XCTest tests: \(error)")
      exit(1)
    }

    Task {
      do {
        try await SwiftTestingRunner.run()
      } catch {
        print("Fatal error running swift-testing tests: \(error)")
        exit(1)
      }

      let recorder = XUnitTestRecorder.shared
      guard recorder.didTestsRun else {
        print("ERROR: No tests were discovered.")
        exit(1)
      }

      do {
        try recorder.writeXML()
      } catch {
        print("Fatal error writing test results to XML: \(error)")
        exit(1)
      }

      exit(recorder.hasFailure ? 1 : 0)
    }

    _asyncMainDrainQueue()
  }
}
