load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

licenses(["notice"])

# swift_proto_utils

bzl_library(
    name = "swift_proto_utils",
    srcs = ["swift_proto_utils.bzl"],
    visibility = ["//swift:__subpackages__"],
    deps = [
        "@bazel_skylib//lib:paths",
    ],
)
